version: '3.8'

services:
  # Microsoft Presidio Analyzer Service
  presidio-analyzer:
    image: mcr.microsoft.com/presidio-analyzer:latest
    ports:
      - "5002:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - text-anonymizer-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Microsoft Presidio Anonymizer Service
  presidio-anonymizer:
    image: mcr.microsoft.com/presidio-anonymizer:latest
    ports:
      - "5001:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - text-anonymizer-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Text Anonymizer Web Application
  text-anonymizer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - PRESIDIO_ANALYZER_URL=http://presidio-analyzer:3000/analyze
      - PRESIDIO_ANONYMIZER_URL=http://presidio-anonymizer:3000/anonymize
    restart: unless-stopped
    networks:
      - text-anonymizer-network
    depends_on:
      presidio-analyzer:
        condition: service_healthy
      presidio-anonymizer:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/analyze"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development version (optional)
  text-anonymizer-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - PRESIDIO_ANALYZER_URL=http://presidio-analyzer:3000
      - PRESIDIO_ANONYMIZER_URL=http://presidio-anonymizer:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - text-anonymizer-network
    depends_on:
      presidio-analyzer:
        condition: service_healthy
      presidio-anonymizer:
        condition: service_healthy
    profiles:
      - dev

networks:
  text-anonymizer-network:
    driver: bridge
